### ISSUE TITLE
Difference between bubblewrap and linux-user-chroot

### ISSUE THREAD

**Issue by cayolblake** [containers/bubblewrap#533] opened 2022-10-07 08:40 UTC
@rusty-snake experiencing with bwrap, I'm reaching to the conclusion that it's just a wrapper code around `linux-user-chroot`

I didn't check the code yet, but, if that's the case, is there any additional features/capabilities that would make one use any of each?

Appreciate the clarification!

**Comment by smcv** [comment] 2022-10-07 08:45
> I'm reaching to the conclusion that it's just a wrapper code around linux-user-chroot

It is not: it's more like a reimplementation of linux-user-chroot.

> is there any additional features/capabilities

The most obvious are "doesn't always need to be setuid root" and "is maintained". Beyond that, see the man page and source code for details.

This is an issue tracker, not a forum, so I'm closing this as not a bug.

**Closed** 2022-10-07 08:53 UTC
